### ISSUE TITLE
libgd security issues and official bug

### ISSUE THREAD

**Issue by Joungkyun** [OOPS-ORG-PHP/mod_korean#6]
## Abstract

mod_korean's libgd is based on php 7.0.1's libgd. The list below lists the 7.0.1 libgd bug fixes and security bug fixes.

## Required revision history

___04 Jan 2018 PHP 7.0.27:___

- [x] Fixed #75571 Potential infinite loop in gdImageCreateFromGifCtx.

___28 Sep 2017 PHP 7.0.24:___

- [x] Fixed #75124 gdImageGrayScale() may produce colors.
- [x] Fixed #75139 libgd/gd_interpolation.c:1786: suspicious if ?.

___06 Jul 2017 PHP 7.0.21:___

- [x] Fixed #74435 Buffer over-read into uninitialized memory.

___11 May 2017 PHP 7.0.19:___

- [x] Fixed #74343 compile fails on solaris 11 with system gd2 library.

___16 Mar 2017 PHP 7.0.17:___

- [x] Fixed #74031 ReflectionFunction for imagepng is missing last two parameters.

___16 Feb 2017 PHP 7.0.16:___

- [x] Fixed #73968 Premature failing of XBM reading.

___19 Jan 2017 PHP 7.0.15:___

- [x] Fixed #73869 Signed Integer Overflow gd_io.c.
- [x] Fixed #73868 DOS vulnerability in gdImageCreateFromGd2Ctx().

___10 Nov 2016 PHP 7.0.13:___

- [x] Fixed #73213 Integer overflow in imageline() with antialiasing.
- [x] Fixed #73272 imagescale() is not affected by, but affects imagesetinterpolation().
- [x] Fixed #73279 Integer overflow in gdImageScaleBilinearPalette().
- [x] Fixed #73280 Stack Buffer Overflow in GD dynamicGetbuf.
- [x] Fixed #72482 Ilegal write/read access caused by gdImageAALine overflow.
- [x] Fixed #72696 imagefilltoborder stackoverflow on truecolor images.

___13 Oct 2016 PHP 7.0.12:___

- [x] Fixed #67325 imagetruecolortopalette: white is duplicated in palette.
- [x] Fixed #50194 imagettftext broken on transparent background w/o alphablending.
- [x] Fixed #73003 Integer Overflow in gdImageWebpCtx of gd_webp.c.
- [x] Fixed #53504 imagettfbbox gives incorrect values for bounding box.
- [x] Fixed #73157 imagegd2() ignores 3rd param if 4 are given.
- [x] Fixed #73155 imagegd2() writes wrong chunk sizes on boundaries.
- [x] Fixed #73159 imagegd2(): unrecognized formats may result in corrupted files.
- [x] Fixed #73161 imagecreatefromgd2() may leak memory.

___15 Sep 2016 PHP 7.0.11:___

- [x] Fixed #72709 imagesetstyle() causes OOB read for empty $styles.
- [x] Fixed #66005 imagecopy does not support 1bit transparency on truecolor images.
- [x] Fixed #72913 imagecopy() loses single-color transparency on palette images.
- [x] Fixed #68716 possible resource leaks in _php_image_convert().

___18 Aug 2016 PHP 7.0.10:___

- [x] Fixed #72596 imagetypes function won't advertise WEBP support.
- [x] Fixed #72604 imagearc() ignores thickness for full arcs.
- [x] Fixed #70315 500 Server Error but page is fully rendered.
- [x] Fixed #43828 broken transparency of imagearc for truecolor in blendingmode.
- [x] Fixed #66555 Always false condition in ext/gd/libgd/gdkanji.c.
- [x] Fixed #68712 suspicious if-else statements.
- [x] Fixed #72697 select_colors write out-of-bounds.
- [x] Fixed #72730 imagegammacorrect allows arbitrary write access.
- [x] Fixed #72494 imagecropauto out-of-bounds access.

___21 Jul 2016 PHP 7.0.9:___

- [x] Fixed #43475 Thick styled lines have scrambled patterns.
- [x] Fixed #53640 XBM images require width to be multiple of 8.
- [x] Fixed #64641 imagefilledpolygon doesn't draw horizontal line.
- [x] Fixed #72512 gdImageTrueColorToPaletteBody allows arbitrary write/read access.
- [x] Fixed #72519 imagegif/output out-of-bounds access.
- [x] Fixed #72558 Integer overflow error within _gdContributionsAlloc().
- [x] Fixed #72482 Ilegal write/read access caused by gdImageAALine overflow.
- [x] Fixed #72494 imagecropauto out-of-bounds access.

___23 Jun 2016 PHP 7.0.8:___

- [x] Fixed #66387 Stack overflow with imagefilltoborder. (CVE-2015-8874)
- [x] Fixed #72298 pass2_no_dither out-of-bounds access.
- [x] Fixed #72337 invalid dimensions can lead to crash.
- [x] Fixed #72339 Integer Overflow in _gd2GetHeader() resulting in heap overflow. (CVE-2016-5766)
- [x] Fixed #72407 NULL Pointer Dereference at _gdScaleVert.
- [x] Fixed #72446 Integer Overflow in gdImagePaletteToTrueColor() resulting in heap overflow. (CVE-2016-5767)

___26 May 2016 PHP 7.0.7:___

- [x] Fixed #72227 imagescale out-of-bounds read.

___04 Feb 2016 PHP 7.0.3:___

- [x] Improved fix for bug #70976.

___07 Jan 2016 PHP 7.0.2:___

- [x] Fixed #70976 Memory Read via gdImageRotateInterpolated Array Index Out of Bounds. (CVE-2016-1903)

**Comment by Joungkyun** [comment]
updated libgd is based on 7.2.14 and same as 7.3.1
